global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

alerting:
  alertmanagers:
    - static_configs:
        - targets:
rule_files:
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "orderers"
    static_configs:
      - targets: ["172.20.0.13:9444","172.20.0.14:9445","172.20.0.15:9446"]

  - job_name: "Org1 Peers"
    static_configs:
      - targets: ["192.168.64.4:9440"]

  - job_name: "Org2 Peers"
    static_configs:
      - targets: ["192.168.64.7:9442"]

