test:
  name: basic
  description: >-
    This is a duration based benchmark targeting a Hyperledger Fabric network
    using the `basic` NodeJS chaincode
    contract that is interacted with via a Fabric-SDK-Node Gateway. Each test
    round flexes a single chaincode method, and includes a null-operation to act
    as a performance cost baseline.
  workers:
    type: local
    number: 5
  rounds:
    - label: empty-contract-evaluate
      description: >-
        Test an evaluateTransaction() Gateway method against the NodeJS
        `basic` Smart Contract method named `nullResponse`, which
        immediately returns a null response. This represents the fastest
        possible round trip time for an evaluateTransaction() method that does
        not touch the world state or perform any action.
      contractId: basic
      txDuration: 300
      rateControl:
        type: fixed-load
        opts:
          transactionLoad: 100
      workload:
        module: lib/empty-contract.js
        arguments:
          contractId: basic
          consensus: false
    - label: empty-contract-submit
      description: >-
        Test a submitTransaction() Gateway method against the NodeJS
        `basic` Smart Contract method named `nullResponse`, which
        immediately returns a null response. This represents the fastest
        possible round trip time for a submitTransaction() method that does not
        touch the world state or perform any action.
      contractId: basic
      txDuration: 300
      rateControl:
        type: fixed-load
        opts:
          transactionLoad: 100
      workload:
        module: lib/empty-contract.js
        arguments:
          contractId: basic
          consensus: true
    - label: create-asset-1000
      description: >-
        Test a submitTransaction() Gateway method against the NodeJS
        `basic` Smart Contract method named `create`, which performs a
        `putState()` operation on an asset of size 1000 bytes.
      contractId: basic
      txDuration: 300
      rateControl:
        type: fixed-load
        opts:
          transactionLoad: 100
      workload:
        module: lib/create-asset.js
        arguments:
          contractId: basic
          byteSize: 1000
    - label: get-asset-evaluate-1000
      description: >-
        Test a evaluateTransaction() Gateway method against the NodeJS
        `basic` Smart Contract method named `getAsset`. This method
        performs a `getState()` operation for a passed UUID, retrieving as asset
        of size 1000 bytes.
      contractId: basic
      txDuration: 300
      rateControl:
        type: fixed-load
        opts:
          transactionLoad: 100
      workload:
        module: lib/get-asset.js
        arguments:
          contractId: basic
          noSetup: true
          byteSize: 1000
          assets: 500
          consensus: false
    - label: get-asset-submit-1000
      description: >-
        Test a submitTransaction() Gateway method against the NodeJS
        `basic` Smart Contract method named `getAsset`. This method
        performs a `getState()` operation for a passed UUID, retrieving as asset
        of size 1000 bytes. This test includes involvement of the orderer, and
        appending to the ledger.
      contractId: basic
      txDuration: 300
      rateControl:
        type: fixed-load
        opts:
          transactionLoad: 100
      workload:
        module: lib/get-asset.js
        arguments:
          contractId: basic
          noSetup: true
          byteSize: 1000
          assets: 500
          consensus: true
    - label: rich-query-evaluate-0
      description: >-
        Test an evaluateTransaction() Gateway method against the NodeJS
        `basic` Smart Contract method named `paginatedRichQuery`. This
        method performs a paginated rich query, with a passed pagesize of 10 and
        query string that matches no assets in the world state database.
      contractId: basic
      txDuration: 300
      rateControl:
        type: fixed-load
        opts:
          transactionLoad: 100
      workload:
        module: lib/rich-query-asset.js
        arguments:
          contractId: basic
          byteSize: 1000
          pagesize: '10'
          noSetup: true
          nomatch: true
          consensus: false
    - label: rich-query-evaluate-1000
      description: >-
        Test an evaluateTransaction() Gateway method against the NodeJS
        `basic` Smart Contract method named `paginatedRichQuery`. This
        method performs a paginated rich query, with a passed pagesize of 10 and
        query string that matches all assets created by the calling client. Each
        returned asset is of size 1000 bytes.
      contractId: basic
      txDuration: 300
      rateControl:
        type: fixed-load
        opts:
          transactionLoad: 100
      workload:
        module: lib/rich-query-asset.js
        arguments:
          contractId: basic
          byteSize: 1000
          pagesize: '10'
          noSetup: true
          consensus: false
    - label: rich-query-submit-0
      description: >-
        Test a submitTransaction() Gateway method against the NodeJS
        `basic` Smart Contract method named `paginatedRichQuery`. This
        method performs a paginated rich query, with a passed pagesize of 10 and
        query string that matches no assets in the world state database. This
        test includes involvement of the orderer, and appending to the ledger.
      contractId: basic
      txDuration: 300
      rateControl:
        type: fixed-load
        opts:
          transactionLoad: 100
      workload:
        module: lib/rich-query-asset.js
        arguments:
          contractId: basic
          byteSize: 1000
          pagesize: '10'
          noSetup: true
          nomatch: true
          consensus: true
    - label: rich-query-submit-1000
      description: >-
        Test a submitTransaction() Gateway method against the NodeJS
        `basic` Smart Contract method named `paginatedRichQuery`. This
        method performs a paginated rich query, with a passed pagesize of 10 and
        query string that matches all assets created by the calling client. Each
        returned asset is of size 1000 bytes. This test includes involvement of
        the orderer, and appending to the ledger.
      contractId: basic
      txDuration: 300
      rateControl:
        type: fixed-load
        opts:
          transactionLoad: 100
      workload:
        module: lib/rich-query-asset.js
        arguments:
          contractId: basic
          byteSize: 1000
          pagesize: '10'
          noSetup: true
          consensus: true
    - label: range-query-evaluate-0
      description: >-
        Test an evaluateTransaction() Gateway method against the NodeJS
        `basic` Smart Contract method named `paginatedRangeQuery`. This
        method performs a paginated range query that matches no assets in the
        world state database.
      contractId: basic
      txDuration: 300
      rateControl:
        type: fixed-load
        opts:
          transactionLoad: 100
      workload:
        module: lib/range-query-asset.js
        arguments:
          contractId: basic
          byteSize: 1000
          range: 200
          offset: 100
          noSetup: true
          pagesize: '10'
          nomatch: true
          consensus: false
    - label: range-query-evaluate-1000
      description: >-
        Test an evaluateTransaction() Gateway method against the NodeJS
        `basic` Smart Contract method named `paginatedRangeQuery`. This
        method performs a paginated range query, with a passed pagesize of 10
        and a range keys that bound 200 assets created by the calling client.
        Each returned asset is of size 1000 bytes.
      contractId: basic
      txDuration: 300
      rateControl:
        type: fixed-load
        opts:
          transactionLoad: 100
      workload:
        module: lib/range-query-asset.js
        arguments:
          contractId: basic
          byteSize: 1000
          range: 200
          offset: 100
          noSetup: true
          pagesize: '10'
          consensus: false
    - label: range-query-submit-0
      description: >-
        Test a submitTransaction() Gateway method against the NodeJS
        `basic` Smart Contract method named `paginatedRangeQuery`. This
        method performs a paginated range query that matches no items in the
        world state database. This test includes involvement of the orderer, and
        appending to the ledger.
      contractId: basic
      txDuration: 300
      rateControl:
        type: fixed-load
        opts:
          transactionLoad: 100
      workload:
        module: lib/range-query-asset.js
        arguments:
          contractId: basic
          byteSize: 1000
          range: 200
          offset: 100
          noSetup: true
          pagesize: '10'
          nomatch: true
          consensus: true
    - label: range-query-submit-1000
      description: >-
        Test a submitTransaction() Gateway method against the NodeJS
        `basic` Smart Contract method named `paginatedRangeQuery`. This
        method performs a paginated range query, with a passed pagesize of 10
        and a range keys that bound 200 assets created by the calling client.
        Each returned asset is of size 1000 bytes. This test includes
        involvement of the orderer, and appending to the ledger.
      contractId: basic
      txDuration: 300
      rateControl:
        type: fixed-load
        opts:
          transactionLoad: 100
      workload:
        module: lib/range-query-asset.js
        arguments:
          contractId: basic
          byteSize: 1000
          range: 200
          offset: 100
          noSetup: true
          pagesize: '10'
          consensus: true
monitors:
    resource:
    - module: docker
      options:
        interval: 4
        containers: ['all']